### ISSUE TITLE
Longstanding Todo List

### ISSUE THREAD

**Issue by pluto-bell** [jnq-t/all-music-is-microtonal#22]
## General
- [ ]  discuss moving UI functions into separate folder for organization. they currently live in the `use_cases` folder
- [ ]  discuss the removal of `Author` and `isPreset` on `Class Scale` and `generateScale.js`
    - `Author`: should only be used if user is signed in and saving scale; the author name should be pulled in dynamically from user account 
    - `isPreset`: should only be for admins
- [ ] discuss having more than one keyboard on DOM
   - are there good use cases for this?
   - if so, pros vs cons
- [ ]  create "info" icons, for example: what does detune/ratio/sustain edit mode do, what's an octave span, etc.
   -  "hover" & "click" functionality

## Scale
- [ ]  must have a name for scale save
- [ ]  check if scale name already exists in DB

## Keyboard UI
- [ ]  fix issue on `generateScale.js` where data from DOM isn't getting pulled in improperly. 
    - For example: the author `value.data` gets set as a value for `isPreset`
    - Currently have a `console.log` in place to show the `new Scale()` being generated. Use this to reference the describe issue
- [ ] remove and replace `mock_octave` and `mock_length`. Should be reduced to ONE variable. Initially separated for testing purposes.
   - `mock_octave` was placed at 24 so I could technically see two octaves (variable name is not accurate);
   - `mock_length` was being used to place Detune and Ratio modifiers on first octave only;
- [ ] add the scale degree to each keys `innerHTML`.
   - reference current microtonal site
   - all 1st scale degrees are 'square' (zero border-radius)
- [ ] when detune or ratio is used on a key change ALL octaves and re-write frequency 
- [ ] add the approximate scale degree name to key `innerHTML`, e.g. C## Cb
- [ ] build out top and side navigation functionality
   - abstract into utility functions where possible 
- [ ] build out modifier functionality so that sustain, detune, and ratio only show when those items are checked off in the side nav
- [ ] create functionality to show additional octave or remove an octave from keyboard: `+/-`
- [ ] create functionality for saving and deleting a keyboard 
   - 1. delete from DOM
   - 2. if scale exists in DB, destroy
- [ ] remove `addScaleToDatabase` form `generateScale.js` and place in separate file 
- [ ] long term: refactor
- [ ] map keys to computer keyboard. will allow users to play a chord progression easily
   - discuss how to create this
- [ ] long term: random scale generator
- [ ] add little indicators that show sustain/detune/ratio mode is being used?

## User & Non-user UI
- [ ] create a user class
- [ ] create a function to validate if user is signed in or not
   - signed in users can save scales to our database
   - signed out users can save to local storage
- [ ] create local storage save for users without accounts
   - make sure the user is aware of potential erasure of scale when using localStorage and suggest "signing up" for a more permanent save
- [ ] allow users to copy a saved scale to their own account, so they can modify it as desired
- [ ] discuss: if a non-user signs up, transfer any localStorage scales they have to their new account

## Error Handling
- [ ] Scale name already exists
   - turn all scale names to lowercase before handling
   - if scale name exists, provide a link to existing scale incase the user can just use someone else's saved version
   - should check DB and localStorage?
- [ ] Username already exists
   - turn all usernames to lowercase before handling
- [ ] Scale length too long (if we set a max length?)

## Back-End
- [ ]  Data normalization
- [ ] Create a user table
- [ ] Create presets
